# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PlayCreator.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFontComboBox, QFormLayout,
    QGridLayout, QGroupBox, QHBoxLayout, QLabel,
    QLayout, QLineEdit, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpacerItem, QStatusBar, QTabWidget,
    QToolBar, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1466, 1000)
        MainWindow.setMinimumSize(QSize(1466, 1000))
        self.action_save = QAction(MainWindow)
        self.action_save.setObjectName(u"action_save")
        self.action_save.setEnabled(False)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        self.action_presentation_mode = QAction(MainWindow)
        self.action_presentation_mode.setObjectName(u"action_presentation_mode")
        self.action_presentation_mode.setCheckable(True)
        self.action_presentation_mode.setEnabled(True)
        self.action_QB_Wrist = QAction(MainWindow)
        self.action_QB_Wrist.setObjectName(u"action_QB_Wrist")
        self.action_QB_Wrist.setEnabled(False)
        self.action_light_theme = QAction(MainWindow)
        self.action_light_theme.setObjectName(u"action_light_theme")
        self.action_light_theme.setCheckable(True)
        self.action_dark_theme = QAction(MainWindow)
        self.action_dark_theme.setObjectName(u"action_dark_theme")
        self.action_dark_theme.setCheckable(True)
        self.action_dark_theme.setChecked(False)
        self.action_new_scheme = QAction(MainWindow)
        self.action_new_scheme.setObjectName(u"action_new_scheme")
        self.action_new_scheme.setEnabled(True)
        self.action_save_all = QAction(MainWindow)
        self.action_save_all.setObjectName(u"action_save_all")
        self.action_save_all.setEnabled(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_7 = QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.label_current_zoom = QLabel(self.centralwidget)
        self.label_current_zoom.setObjectName(u"label_current_zoom")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_current_zoom.sizePolicy().hasHeightForWidth())
        self.label_current_zoom.setSizePolicy(sizePolicy)
        self.label_current_zoom.setMinimumSize(QSize(160, 25))
        self.label_current_zoom.setMaximumSize(QSize(160, 25))
        font = QFont()
        font.setPointSize(10)
        self.label_current_zoom.setFont(font)

        self.verticalLayout.addWidget(self.label_current_zoom)

        self.tabWidget_game_type = QTabWidget(self.centralwidget)
        self.tabWidget_game_type.setObjectName(u"tabWidget_game_type")
        sizePolicy.setHeightForWidth(self.tabWidget_game_type.sizePolicy().hasHeightForWidth())
        self.tabWidget_game_type.setSizePolicy(sizePolicy)
        self.tabWidget_game_type.setMinimumSize(QSize(360, 730))
        self.tabWidget_game_type.setMaximumSize(QSize(60000, 60000))
        self.tabWidget_game_type.setFont(font)
        self.tab_football = QWidget()
        self.tab_football.setObjectName(u"tab_football")
        self.gridLayout_6 = QGridLayout(self.tab_football)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_football = QGridLayout()
        self.gridLayout_football.setObjectName(u"gridLayout_football")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton_add_additional_off_football = QPushButton(self.tab_football)
        self.pushButton_add_additional_off_football.setObjectName(u"pushButton_add_additional_off_football")
        self.pushButton_add_additional_off_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_add_additional_off_football.sizePolicy().hasHeightForWidth())
        self.pushButton_add_additional_off_football.setSizePolicy(sizePolicy)
        self.pushButton_add_additional_off_football.setMinimumSize(QSize(30, 25))
        self.pushButton_add_additional_off_football.setMaximumSize(QSize(30, 25))
        self.pushButton_add_additional_off_football.setFont(font)

        self.horizontalLayout.addWidget(self.pushButton_add_additional_off_football)

        self.pushButton_del_additional_off_football = QPushButton(self.tab_football)
        self.pushButton_del_additional_off_football.setObjectName(u"pushButton_del_additional_off_football")
        self.pushButton_del_additional_off_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_del_additional_off_football.sizePolicy().hasHeightForWidth())
        self.pushButton_del_additional_off_football.setSizePolicy(sizePolicy)
        self.pushButton_del_additional_off_football.setMinimumSize(QSize(30, 25))
        self.pushButton_del_additional_off_football.setMaximumSize(QSize(30, 25))
        self.pushButton_del_additional_off_football.setFont(font)

        self.horizontalLayout.addWidget(self.pushButton_del_additional_off_football)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_6)


        self.gridLayout_football.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.pushButton_place_second_team_football = QPushButton(self.tab_football)
        self.pushButton_place_second_team_football.setObjectName(u"pushButton_place_second_team_football")
        self.pushButton_place_second_team_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_place_second_team_football.sizePolicy().hasHeightForWidth())
        self.pushButton_place_second_team_football.setSizePolicy(sizePolicy)
        self.pushButton_place_second_team_football.setMinimumSize(QSize(160, 25))
        self.pushButton_place_second_team_football.setMaximumSize(QSize(160, 25))
        self.pushButton_place_second_team_football.setFont(font)

        self.gridLayout_football.addWidget(self.pushButton_place_second_team_football, 2, 0, 1, 1)

        self.pushButton_delete_second_team_football = QPushButton(self.tab_football)
        self.pushButton_delete_second_team_football.setObjectName(u"pushButton_delete_second_team_football")
        self.pushButton_delete_second_team_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_delete_second_team_football.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_second_team_football.setSizePolicy(sizePolicy)
        self.pushButton_delete_second_team_football.setMinimumSize(QSize(160, 25))
        self.pushButton_delete_second_team_football.setMaximumSize(QSize(160, 25))
        self.pushButton_delete_second_team_football.setFont(font)

        self.gridLayout_football.addWidget(self.pushButton_delete_second_team_football, 2, 1, 1, 1)

        self.verticalLayout_place_first_team_football_combo = QVBoxLayout()
        self.verticalLayout_place_first_team_football_combo.setObjectName(u"verticalLayout_place_first_team_football_combo")
        self.label_place_players_football = QLabel(self.tab_football)
        self.label_place_players_football.setObjectName(u"label_place_players_football")
        sizePolicy.setHeightForWidth(self.label_place_players_football.sizePolicy().hasHeightForWidth())
        self.label_place_players_football.setSizePolicy(sizePolicy)
        self.label_place_players_football.setMinimumSize(QSize(160, 25))
        self.label_place_players_football.setMaximumSize(QSize(160, 25))
        self.label_place_players_football.setFont(font)

        self.verticalLayout_place_first_team_football_combo.addWidget(self.label_place_players_football)

        self.comboBox_team_type_football = QComboBox(self.tab_football)
        self.comboBox_team_type_football.addItem("")
        self.comboBox_team_type_football.addItem("")
        self.comboBox_team_type_football.addItem("")
        self.comboBox_team_type_football.addItem("")
        self.comboBox_team_type_football.setObjectName(u"comboBox_team_type_football")
        self.comboBox_team_type_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.comboBox_team_type_football.sizePolicy().hasHeightForWidth())
        self.comboBox_team_type_football.setSizePolicy(sizePolicy)
        self.comboBox_team_type_football.setMinimumSize(QSize(160, 25))
        self.comboBox_team_type_football.setMaximumSize(QSize(160, 25))
        self.comboBox_team_type_football.setFont(font)

        self.verticalLayout_place_first_team_football_combo.addWidget(self.comboBox_team_type_football)


        self.gridLayout_football.addLayout(self.verticalLayout_place_first_team_football_combo, 0, 0, 1, 1)

        self.pushButton_delete_all_players_football = QPushButton(self.tab_football)
        self.pushButton_delete_all_players_football.setObjectName(u"pushButton_delete_all_players_football")
        self.pushButton_delete_all_players_football.setEnabled(False)
        self.pushButton_delete_all_players_football.setMinimumSize(QSize(160, 25))
        self.pushButton_delete_all_players_football.setMaximumSize(QSize(160, 25))
        self.pushButton_delete_all_players_football.setFont(font)

        self.gridLayout_football.addWidget(self.pushButton_delete_all_players_football, 3, 0, 1, 1)

        self.verticalLayout_yards_football = QVBoxLayout()
        self.verticalLayout_yards_football.setObjectName(u"verticalLayout_yards_football")
        self.label_yards_football = QLabel(self.tab_football)
        self.label_yards_football.setObjectName(u"label_yards_football")
        sizePolicy.setHeightForWidth(self.label_yards_football.sizePolicy().hasHeightForWidth())
        self.label_yards_football.setSizePolicy(sizePolicy)
        self.label_yards_football.setMinimumSize(QSize(150, 25))
        self.label_yards_football.setMaximumSize(QSize(150, 25))
        self.label_yards_football.setFont(font)

        self.verticalLayout_yards_football.addWidget(self.label_yards_football)

        self.lineEdit_yards_football = QLineEdit(self.tab_football)
        self.lineEdit_yards_football.setObjectName(u"lineEdit_yards_football")
        self.lineEdit_yards_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.lineEdit_yards_football.sizePolicy().hasHeightForWidth())
        self.lineEdit_yards_football.setSizePolicy(sizePolicy)
        self.lineEdit_yards_football.setMinimumSize(QSize(160, 25))
        self.lineEdit_yards_football.setMaximumSize(QSize(160, 25))
        self.lineEdit_yards_football.setFont(font)
        self.lineEdit_yards_football.setMaxLength(2)

        self.verticalLayout_yards_football.addWidget(self.lineEdit_yards_football)


        self.gridLayout_football.addLayout(self.verticalLayout_yards_football, 0, 1, 1, 1)

        self.pushButton_place_first_team_football = QPushButton(self.tab_football)
        self.pushButton_place_first_team_football.setObjectName(u"pushButton_place_first_team_football")
        self.pushButton_place_first_team_football.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_place_first_team_football.sizePolicy().hasHeightForWidth())
        self.pushButton_place_first_team_football.setSizePolicy(sizePolicy)
        self.pushButton_place_first_team_football.setMinimumSize(QSize(160, 25))
        self.pushButton_place_first_team_football.setMaximumSize(QSize(160, 25))
        self.pushButton_place_first_team_football.setFont(font)

        self.gridLayout_football.addWidget(self.pushButton_place_first_team_football, 1, 0, 1, 1)


        self.gridLayout_6.addLayout(self.gridLayout_football, 0, 0, 1, 2)

        self.listWidget_schemes_football = QListWidget(self.tab_football)
        self.listWidget_schemes_football.setObjectName(u"listWidget_schemes_football")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.listWidget_schemes_football.sizePolicy().hasHeightForWidth())
        self.listWidget_schemes_football.setSizePolicy(sizePolicy1)
        self.listWidget_schemes_football.setMinimumSize(QSize(326, 300))
        self.listWidget_schemes_football.setMaximumSize(QSize(326, 16777215))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(15)
        self.listWidget_schemes_football.setFont(font1)

        self.gridLayout_6.addWidget(self.listWidget_schemes_football, 1, 0, 1, 2)

        self.pushButton_edit_scheme_football = QPushButton(self.tab_football)
        self.pushButton_edit_scheme_football.setObjectName(u"pushButton_edit_scheme_football")
        self.pushButton_edit_scheme_football.setEnabled(False)
        self.pushButton_edit_scheme_football.setMinimumSize(QSize(200, 25))
        self.pushButton_edit_scheme_football.setMaximumSize(QSize(16777215, 25))

        self.gridLayout_6.addWidget(self.pushButton_edit_scheme_football, 2, 0, 1, 2)

        self.pushButton_add_scheme_football = QPushButton(self.tab_football)
        self.pushButton_add_scheme_football.setObjectName(u"pushButton_add_scheme_football")
        sizePolicy2 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_add_scheme_football.sizePolicy().hasHeightForWidth())
        self.pushButton_add_scheme_football.setSizePolicy(sizePolicy2)
        self.pushButton_add_scheme_football.setMinimumSize(QSize(87, 25))
        self.pushButton_add_scheme_football.setMaximumSize(QSize(160, 25))
        font2 = QFont()
        font2.setPointSize(12)
        self.pushButton_add_scheme_football.setFont(font2)

        self.gridLayout_6.addWidget(self.pushButton_add_scheme_football, 3, 0, 1, 1)

        self.pushButton_delete_scheme_football = QPushButton(self.tab_football)
        self.pushButton_delete_scheme_football.setObjectName(u"pushButton_delete_scheme_football")
        self.pushButton_delete_scheme_football.setEnabled(False)
        sizePolicy3 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.pushButton_delete_scheme_football.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_scheme_football.setSizePolicy(sizePolicy3)
        self.pushButton_delete_scheme_football.setMinimumSize(QSize(87, 25))
        self.pushButton_delete_scheme_football.setMaximumSize(QSize(160, 25))
        self.pushButton_delete_scheme_football.setFont(font2)

        self.gridLayout_6.addWidget(self.pushButton_delete_scheme_football, 3, 1, 1, 1)

        self.pushButton_scheme_move_up_football = QPushButton(self.tab_football)
        self.pushButton_scheme_move_up_football.setObjectName(u"pushButton_scheme_move_up_football")
        self.pushButton_scheme_move_up_football.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.pushButton_scheme_move_up_football.sizePolicy().hasHeightForWidth())
        self.pushButton_scheme_move_up_football.setSizePolicy(sizePolicy2)
        self.pushButton_scheme_move_up_football.setMinimumSize(QSize(87, 25))
        self.pushButton_scheme_move_up_football.setMaximumSize(QSize(160, 25))
        self.pushButton_scheme_move_up_football.setFont(font)

        self.gridLayout_6.addWidget(self.pushButton_scheme_move_up_football, 4, 0, 1, 1)

        self.pushButton_scheme_move_down_football = QPushButton(self.tab_football)
        self.pushButton_scheme_move_down_football.setObjectName(u"pushButton_scheme_move_down_football")
        self.pushButton_scheme_move_down_football.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.pushButton_scheme_move_down_football.sizePolicy().hasHeightForWidth())
        self.pushButton_scheme_move_down_football.setSizePolicy(sizePolicy2)
        self.pushButton_scheme_move_down_football.setMinimumSize(QSize(87, 25))
        self.pushButton_scheme_move_down_football.setMaximumSize(QSize(160, 25))
        self.pushButton_scheme_move_down_football.setFont(font)

        self.gridLayout_6.addWidget(self.pushButton_scheme_move_down_football, 4, 1, 1, 1)

        self.tabWidget_game_type.addTab(self.tab_football, "")
        self.tab_flag = QWidget()
        self.tab_flag.setObjectName(u"tab_flag")
        self.gridLayout = QGridLayout(self.tab_flag)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout_flag = QGridLayout()
        self.gridLayout_flag.setObjectName(u"gridLayout_flag")
        self.horizontalLayout_place_defence_flag = QHBoxLayout()
        self.horizontalLayout_place_defence_flag.setObjectName(u"horizontalLayout_place_defence_flag")
        self.pushButton_place_def_team_flag = QPushButton(self.tab_flag)
        self.pushButton_place_def_team_flag.setObjectName(u"pushButton_place_def_team_flag")
        self.pushButton_place_def_team_flag.setEnabled(False)
        self.pushButton_place_def_team_flag.setMinimumSize(QSize(160, 25))
        self.pushButton_place_def_team_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_place_def_team_flag.setFont(font)

        self.horizontalLayout_place_defence_flag.addWidget(self.pushButton_place_def_team_flag)

        self.pushButton_delete_def_team_flag = QPushButton(self.tab_flag)
        self.pushButton_delete_def_team_flag.setObjectName(u"pushButton_delete_def_team_flag")
        self.pushButton_delete_def_team_flag.setEnabled(False)
        self.pushButton_delete_def_team_flag.setMinimumSize(QSize(150, 25))
        self.pushButton_delete_def_team_flag.setMaximumSize(QSize(150, 25))
        self.pushButton_delete_def_team_flag.setFont(font)

        self.horizontalLayout_place_defence_flag.addWidget(self.pushButton_delete_def_team_flag)

        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_place_defence_flag.addItem(self.horizontalSpacer_5)


        self.gridLayout_flag.addLayout(self.horizontalLayout_place_defence_flag, 2, 0, 1, 1)

        self.verticalLayout_yards_flag = QVBoxLayout()
        self.verticalLayout_yards_flag.setObjectName(u"verticalLayout_yards_flag")
        self.label_yards_flag = QLabel(self.tab_flag)
        self.label_yards_flag.setObjectName(u"label_yards_flag")
        self.label_yards_flag.setMinimumSize(QSize(160, 25))
        self.label_yards_flag.setMaximumSize(QSize(160, 25))
        self.label_yards_flag.setFont(font)

        self.verticalLayout_yards_flag.addWidget(self.label_yards_flag)

        self.lineEdit_yards_flag = QLineEdit(self.tab_flag)
        self.lineEdit_yards_flag.setObjectName(u"lineEdit_yards_flag")
        self.lineEdit_yards_flag.setEnabled(False)
        self.lineEdit_yards_flag.setMinimumSize(QSize(160, 25))
        self.lineEdit_yards_flag.setMaximumSize(QSize(160, 25))
        self.lineEdit_yards_flag.setFont(font)
        self.lineEdit_yards_flag.setMaxLength(2)

        self.verticalLayout_yards_flag.addWidget(self.lineEdit_yards_flag)


        self.gridLayout_flag.addLayout(self.verticalLayout_yards_flag, 0, 0, 1, 1)

        self.pushButton_delete_all_players_flag = QPushButton(self.tab_flag)
        self.pushButton_delete_all_players_flag.setObjectName(u"pushButton_delete_all_players_flag")
        self.pushButton_delete_all_players_flag.setEnabled(False)
        self.pushButton_delete_all_players_flag.setMinimumSize(QSize(160, 25))
        self.pushButton_delete_all_players_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_delete_all_players_flag.setFont(font)

        self.gridLayout_flag.addWidget(self.pushButton_delete_all_players_flag, 3, 0, 1, 1)

        self.horizontalLayout_place_offence_flag = QHBoxLayout()
        self.horizontalLayout_place_offence_flag.setObjectName(u"horizontalLayout_place_offence_flag")
        self.pushButton_place_off_team_flag = QPushButton(self.tab_flag)
        self.pushButton_place_off_team_flag.setObjectName(u"pushButton_place_off_team_flag")
        self.pushButton_place_off_team_flag.setEnabled(False)
        self.pushButton_place_off_team_flag.setMinimumSize(QSize(160, 25))
        self.pushButton_place_off_team_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_place_off_team_flag.setFont(font)

        self.horizontalLayout_place_offence_flag.addWidget(self.pushButton_place_off_team_flag)

        self.pushButton_add_additional_off_flag = QPushButton(self.tab_flag)
        self.pushButton_add_additional_off_flag.setObjectName(u"pushButton_add_additional_off_flag")
        self.pushButton_add_additional_off_flag.setEnabled(False)
        self.pushButton_add_additional_off_flag.setMinimumSize(QSize(30, 25))
        self.pushButton_add_additional_off_flag.setMaximumSize(QSize(30, 25))
        self.pushButton_add_additional_off_flag.setFont(font)

        self.horizontalLayout_place_offence_flag.addWidget(self.pushButton_add_additional_off_flag)

        self.pushButton_del_additional_off_flag = QPushButton(self.tab_flag)
        self.pushButton_del_additional_off_flag.setObjectName(u"pushButton_del_additional_off_flag")
        self.pushButton_del_additional_off_flag.setEnabled(False)
        self.pushButton_del_additional_off_flag.setMinimumSize(QSize(30, 25))
        self.pushButton_del_additional_off_flag.setMaximumSize(QSize(30, 25))
        self.pushButton_del_additional_off_flag.setFont(font)

        self.horizontalLayout_place_offence_flag.addWidget(self.pushButton_del_additional_off_flag)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_place_offence_flag.addItem(self.horizontalSpacer_4)


        self.gridLayout_flag.addLayout(self.horizontalLayout_place_offence_flag, 1, 0, 1, 1)


        self.gridLayout.addLayout(self.gridLayout_flag, 0, 0, 1, 2)

        self.listWidget_schemes_flag = QListWidget(self.tab_flag)
        self.listWidget_schemes_flag.setObjectName(u"listWidget_schemes_flag")
        sizePolicy1.setHeightForWidth(self.listWidget_schemes_flag.sizePolicy().hasHeightForWidth())
        self.listWidget_schemes_flag.setSizePolicy(sizePolicy1)
        self.listWidget_schemes_flag.setMinimumSize(QSize(326, 300))
        self.listWidget_schemes_flag.setMaximumSize(QSize(326, 16777215))
        self.listWidget_schemes_flag.setFont(font1)

        self.gridLayout.addWidget(self.listWidget_schemes_flag, 1, 0, 1, 2)

        self.pushButton_edit_scheme_flag = QPushButton(self.tab_flag)
        self.pushButton_edit_scheme_flag.setObjectName(u"pushButton_edit_scheme_flag")
        self.pushButton_edit_scheme_flag.setEnabled(False)
        self.pushButton_edit_scheme_flag.setMinimumSize(QSize(200, 25))
        self.pushButton_edit_scheme_flag.setMaximumSize(QSize(16777215, 25))

        self.gridLayout.addWidget(self.pushButton_edit_scheme_flag, 2, 0, 1, 2)

        self.pushButton_add_scheme_flag = QPushButton(self.tab_flag)
        self.pushButton_add_scheme_flag.setObjectName(u"pushButton_add_scheme_flag")
        sizePolicy2.setHeightForWidth(self.pushButton_add_scheme_flag.sizePolicy().hasHeightForWidth())
        self.pushButton_add_scheme_flag.setSizePolicy(sizePolicy2)
        self.pushButton_add_scheme_flag.setMinimumSize(QSize(87, 25))
        self.pushButton_add_scheme_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_add_scheme_flag.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_add_scheme_flag, 3, 0, 1, 1)

        self.pushButton_delete_scheme_flag = QPushButton(self.tab_flag)
        self.pushButton_delete_scheme_flag.setObjectName(u"pushButton_delete_scheme_flag")
        self.pushButton_delete_scheme_flag.setEnabled(False)
        sizePolicy3.setHeightForWidth(self.pushButton_delete_scheme_flag.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_scheme_flag.setSizePolicy(sizePolicy3)
        self.pushButton_delete_scheme_flag.setMinimumSize(QSize(87, 25))
        self.pushButton_delete_scheme_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_delete_scheme_flag.setFont(font2)

        self.gridLayout.addWidget(self.pushButton_delete_scheme_flag, 3, 1, 1, 1)

        self.pushButton_scheme_move_up_flag = QPushButton(self.tab_flag)
        self.pushButton_scheme_move_up_flag.setObjectName(u"pushButton_scheme_move_up_flag")
        self.pushButton_scheme_move_up_flag.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.pushButton_scheme_move_up_flag.sizePolicy().hasHeightForWidth())
        self.pushButton_scheme_move_up_flag.setSizePolicy(sizePolicy2)
        self.pushButton_scheme_move_up_flag.setMinimumSize(QSize(87, 25))
        self.pushButton_scheme_move_up_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_scheme_move_up_flag.setFont(font)

        self.gridLayout.addWidget(self.pushButton_scheme_move_up_flag, 4, 0, 1, 1)

        self.pushButton_scheme_move_down_flag = QPushButton(self.tab_flag)
        self.pushButton_scheme_move_down_flag.setObjectName(u"pushButton_scheme_move_down_flag")
        self.pushButton_scheme_move_down_flag.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.pushButton_scheme_move_down_flag.sizePolicy().hasHeightForWidth())
        self.pushButton_scheme_move_down_flag.setSizePolicy(sizePolicy2)
        self.pushButton_scheme_move_down_flag.setMinimumSize(QSize(87, 25))
        self.pushButton_scheme_move_down_flag.setMaximumSize(QSize(160, 25))
        self.pushButton_scheme_move_down_flag.setFont(font)

        self.gridLayout.addWidget(self.pushButton_scheme_move_down_flag, 4, 1, 1, 1)

        self.tabWidget_game_type.addTab(self.tab_flag, "")

        self.verticalLayout.addWidget(self.tabWidget_game_type)


        self.gridLayout_7.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.formLayout_bot = QFormLayout()
        self.formLayout_bot.setObjectName(u"formLayout_bot")
        self.formLayout_bot.setRowWrapPolicy(QFormLayout.WrapLongRows)
        self.formLayout_bot.setHorizontalSpacing(0)
        self.horizontalLayout_painting_2 = QHBoxLayout()
        self.horizontalLayout_painting_2.setSpacing(6)
        self.horizontalLayout_painting_2.setObjectName(u"horizontalLayout_painting_2")
        self.horizontalLayout_painting_2.setSizeConstraint(QLayout.SetFixedSize)
        self.horizontalLayout_painting_2.setContentsMargins(-1, -1, 6, -1)
        self.groupBox_move_erase = QGroupBox(self.centralwidget)
        self.groupBox_move_erase.setObjectName(u"groupBox_move_erase")
        self.groupBox_move_erase.setMinimumSize(QSize(111, 61))
        self.groupBox_move_erase.setMaximumSize(QSize(111, 61))
        self.gridLayout_2 = QGridLayout(self.groupBox_move_erase)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.pushButton_move = QPushButton(self.groupBox_move_erase)
        self.pushButton_move.setObjectName(u"pushButton_move")
        self.pushButton_move.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_move.sizePolicy().hasHeightForWidth())
        self.pushButton_move.setSizePolicy(sizePolicy)
        self.pushButton_move.setMinimumSize(QSize(40, 40))
        self.pushButton_move.setMaximumSize(QSize(40, 40))
        self.pushButton_move.setIconSize(QSize(35, 35))
        self.pushButton_move.setCheckable(True)
        self.pushButton_move.setChecked(True)

        self.gridLayout_2.addWidget(self.pushButton_move, 0, 0, 1, 1)

        self.pushButton_erase = QPushButton(self.groupBox_move_erase)
        self.pushButton_erase.setObjectName(u"pushButton_erase")
        self.pushButton_erase.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_erase.sizePolicy().hasHeightForWidth())
        self.pushButton_erase.setSizePolicy(sizePolicy)
        self.pushButton_erase.setMinimumSize(QSize(40, 40))
        self.pushButton_erase.setMaximumSize(QSize(40, 40))
        self.pushButton_erase.setIconSize(QSize(35, 35))
        self.pushButton_erase.setCheckable(True)

        self.gridLayout_2.addWidget(self.pushButton_erase, 0, 1, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_move_erase)

        self.groupBox_colors = QGroupBox(self.centralwidget)
        self.groupBox_colors.setObjectName(u"groupBox_colors")
        self.groupBox_colors.setMinimumSize(QSize(191, 61))
        self.groupBox_colors.setMaximumSize(QSize(191, 61))
        self.gridLayout_3 = QGridLayout(self.groupBox_colors)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.pushButton_current_color = QPushButton(self.groupBox_colors)
        self.pushButton_current_color.setObjectName(u"pushButton_current_color")
        self.pushButton_current_color.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_current_color.sizePolicy().hasHeightForWidth())
        self.pushButton_current_color.setSizePolicy(sizePolicy)
        self.pushButton_current_color.setMinimumSize(QSize(40, 40))
        self.pushButton_current_color.setMaximumSize(QSize(40, 40))

        self.gridLayout_3.addWidget(self.pushButton_current_color, 0, 0, 1, 1)

        self.gridLayout_colors = QGridLayout()
        self.gridLayout_colors.setSpacing(2)
        self.gridLayout_colors.setObjectName(u"gridLayout_colors")
        self.pushButton_color_10 = QPushButton(self.groupBox_colors)
        self.pushButton_color_10.setObjectName(u"pushButton_color_10")
        self.pushButton_color_10.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_10.sizePolicy().hasHeightForWidth())
        self.pushButton_color_10.setSizePolicy(sizePolicy)
        self.pushButton_color_10.setMinimumSize(QSize(18, 18))
        self.pushButton_color_10.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_10, 1, 4, 1, 1)

        self.pushButton_color_9 = QPushButton(self.groupBox_colors)
        self.pushButton_color_9.setObjectName(u"pushButton_color_9")
        self.pushButton_color_9.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_9.sizePolicy().hasHeightForWidth())
        self.pushButton_color_9.setSizePolicy(sizePolicy)
        self.pushButton_color_9.setMinimumSize(QSize(18, 18))
        self.pushButton_color_9.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_9, 1, 3, 1, 1)

        self.pushButton_color_4 = QPushButton(self.groupBox_colors)
        self.pushButton_color_4.setObjectName(u"pushButton_color_4")
        self.pushButton_color_4.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_4.sizePolicy().hasHeightForWidth())
        self.pushButton_color_4.setSizePolicy(sizePolicy)
        self.pushButton_color_4.setMinimumSize(QSize(18, 18))
        self.pushButton_color_4.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_4, 0, 4, 1, 1)

        self.pushButton_color_6 = QPushButton(self.groupBox_colors)
        self.pushButton_color_6.setObjectName(u"pushButton_color_6")
        self.pushButton_color_6.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_6.sizePolicy().hasHeightForWidth())
        self.pushButton_color_6.setSizePolicy(sizePolicy)
        self.pushButton_color_6.setMinimumSize(QSize(18, 18))
        self.pushButton_color_6.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_6, 1, 0, 1, 1)

        self.pushButton_color_7 = QPushButton(self.groupBox_colors)
        self.pushButton_color_7.setObjectName(u"pushButton_color_7")
        self.pushButton_color_7.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_7.sizePolicy().hasHeightForWidth())
        self.pushButton_color_7.setSizePolicy(sizePolicy)
        self.pushButton_color_7.setMinimumSize(QSize(18, 18))
        self.pushButton_color_7.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_7, 1, 1, 1, 1)

        self.pushButton_color_1 = QPushButton(self.groupBox_colors)
        self.pushButton_color_1.setObjectName(u"pushButton_color_1")
        self.pushButton_color_1.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_1.sizePolicy().hasHeightForWidth())
        self.pushButton_color_1.setSizePolicy(sizePolicy)
        self.pushButton_color_1.setMinimumSize(QSize(18, 18))
        self.pushButton_color_1.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_1, 0, 1, 1, 1)

        self.pushButton_color_8 = QPushButton(self.groupBox_colors)
        self.pushButton_color_8.setObjectName(u"pushButton_color_8")
        self.pushButton_color_8.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_8.sizePolicy().hasHeightForWidth())
        self.pushButton_color_8.setSizePolicy(sizePolicy)
        self.pushButton_color_8.setMinimumSize(QSize(18, 18))
        self.pushButton_color_8.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_8, 1, 2, 1, 1)

        self.pushButton_color_2 = QPushButton(self.groupBox_colors)
        self.pushButton_color_2.setObjectName(u"pushButton_color_2")
        self.pushButton_color_2.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_2.sizePolicy().hasHeightForWidth())
        self.pushButton_color_2.setSizePolicy(sizePolicy)
        self.pushButton_color_2.setMinimumSize(QSize(18, 18))
        self.pushButton_color_2.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_2, 0, 2, 1, 1)

        self.pushButton_color_3 = QPushButton(self.groupBox_colors)
        self.pushButton_color_3.setObjectName(u"pushButton_color_3")
        self.pushButton_color_3.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_3.sizePolicy().hasHeightForWidth())
        self.pushButton_color_3.setSizePolicy(sizePolicy)
        self.pushButton_color_3.setMinimumSize(QSize(18, 18))
        self.pushButton_color_3.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_3, 0, 3, 1, 1)

        self.pushButton_color_0 = QPushButton(self.groupBox_colors)
        self.pushButton_color_0.setObjectName(u"pushButton_color_0")
        self.pushButton_color_0.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_0.sizePolicy().hasHeightForWidth())
        self.pushButton_color_0.setSizePolicy(sizePolicy)
        self.pushButton_color_0.setMinimumSize(QSize(18, 18))
        self.pushButton_color_0.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_0, 0, 0, 1, 1)

        self.pushButton_color_5 = QPushButton(self.groupBox_colors)
        self.pushButton_color_5.setObjectName(u"pushButton_color_5")
        self.pushButton_color_5.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_5.sizePolicy().hasHeightForWidth())
        self.pushButton_color_5.setSizePolicy(sizePolicy)
        self.pushButton_color_5.setMinimumSize(QSize(18, 18))
        self.pushButton_color_5.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_5, 0, 5, 1, 1)

        self.pushButton_color_11 = QPushButton(self.groupBox_colors)
        self.pushButton_color_11.setObjectName(u"pushButton_color_11")
        self.pushButton_color_11.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_color_11.sizePolicy().hasHeightForWidth())
        self.pushButton_color_11.setSizePolicy(sizePolicy)
        self.pushButton_color_11.setMinimumSize(QSize(18, 18))
        self.pushButton_color_11.setMaximumSize(QSize(18, 18))

        self.gridLayout_colors.addWidget(self.pushButton_color_11, 1, 5, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_colors, 0, 1, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_colors)

        self.groupBox_painting = QGroupBox(self.centralwidget)
        self.groupBox_painting.setObjectName(u"groupBox_painting")
        self.groupBox_painting.setMinimumSize(QSize(475, 61))
        self.groupBox_painting.setMaximumSize(QSize(471, 61))
        self.gridLayout_4 = QGridLayout(self.groupBox_painting)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.comboBox_line_thickness = QComboBox(self.groupBox_painting)
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.addItem("")
        self.comboBox_line_thickness.setObjectName(u"comboBox_line_thickness")
        self.comboBox_line_thickness.setEnabled(False)
        sizePolicy.setHeightForWidth(self.comboBox_line_thickness.sizePolicy().hasHeightForWidth())
        self.comboBox_line_thickness.setSizePolicy(sizePolicy)
        self.comboBox_line_thickness.setMinimumSize(QSize(40, 25))
        self.comboBox_line_thickness.setMaximumSize(QSize(40, 25))
        self.comboBox_line_thickness.setFont(font)

        self.gridLayout_4.addWidget(self.comboBox_line_thickness, 0, 0, 1, 1)

        self.pushButton_route = QPushButton(self.groupBox_painting)
        self.pushButton_route.setObjectName(u"pushButton_route")
        self.pushButton_route.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_route.sizePolicy().hasHeightForWidth())
        self.pushButton_route.setSizePolicy(sizePolicy)
        self.pushButton_route.setMinimumSize(QSize(40, 40))
        self.pushButton_route.setMaximumSize(QSize(40, 40))
        self.pushButton_route.setIconSize(QSize(35, 35))
        self.pushButton_route.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_route, 0, 1, 1, 1)

        self.pushButton_block = QPushButton(self.groupBox_painting)
        self.pushButton_block.setObjectName(u"pushButton_block")
        self.pushButton_block.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_block.sizePolicy().hasHeightForWidth())
        self.pushButton_block.setSizePolicy(sizePolicy)
        self.pushButton_block.setMinimumSize(QSize(40, 40))
        self.pushButton_block.setMaximumSize(QSize(40, 40))
        self.pushButton_block.setIconSize(QSize(35, 35))
        self.pushButton_block.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_block, 0, 2, 1, 1)

        self.pushButton_motion = QPushButton(self.groupBox_painting)
        self.pushButton_motion.setObjectName(u"pushButton_motion")
        self.pushButton_motion.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_motion.sizePolicy().hasHeightForWidth())
        self.pushButton_motion.setSizePolicy(sizePolicy)
        self.pushButton_motion.setMinimumSize(QSize(40, 40))
        self.pushButton_motion.setMaximumSize(QSize(40, 40))
        self.pushButton_motion.setIconSize(QSize(35, 35))
        self.pushButton_motion.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_motion, 0, 3, 1, 1)

        self.pushButton_delete_actions = QPushButton(self.groupBox_painting)
        self.pushButton_delete_actions.setObjectName(u"pushButton_delete_actions")
        self.pushButton_delete_actions.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_delete_actions.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_actions.setSizePolicy(sizePolicy)
        self.pushButton_delete_actions.setMinimumSize(QSize(40, 40))
        self.pushButton_delete_actions.setMaximumSize(QSize(40, 40))
        self.pushButton_delete_actions.setIconSize(QSize(35, 35))

        self.gridLayout_4.addWidget(self.pushButton_delete_actions, 0, 4, 1, 1)

        self.pushButton_rectangle = QPushButton(self.groupBox_painting)
        self.pushButton_rectangle.setObjectName(u"pushButton_rectangle")
        self.pushButton_rectangle.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_rectangle.sizePolicy().hasHeightForWidth())
        self.pushButton_rectangle.setSizePolicy(sizePolicy)
        self.pushButton_rectangle.setMinimumSize(QSize(40, 40))
        self.pushButton_rectangle.setMaximumSize(QSize(40, 40))
        self.pushButton_rectangle.setIconSize(QSize(35, 35))
        self.pushButton_rectangle.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_rectangle, 0, 5, 1, 1)

        self.pushButton_ellipse = QPushButton(self.groupBox_painting)
        self.pushButton_ellipse.setObjectName(u"pushButton_ellipse")
        self.pushButton_ellipse.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_ellipse.sizePolicy().hasHeightForWidth())
        self.pushButton_ellipse.setSizePolicy(sizePolicy)
        self.pushButton_ellipse.setMinimumSize(QSize(40, 40))
        self.pushButton_ellipse.setMaximumSize(QSize(40, 40))
        self.pushButton_ellipse.setIconSize(QSize(35, 35))
        self.pushButton_ellipse.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_ellipse, 0, 6, 1, 1)

        self.pushButton_delete_figures = QPushButton(self.groupBox_painting)
        self.pushButton_delete_figures.setObjectName(u"pushButton_delete_figures")
        self.pushButton_delete_figures.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_delete_figures.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_figures.setSizePolicy(sizePolicy)
        self.pushButton_delete_figures.setMinimumSize(QSize(40, 40))
        self.pushButton_delete_figures.setMaximumSize(QSize(40, 40))
        self.pushButton_delete_figures.setIconSize(QSize(35, 35))
        self.pushButton_delete_figures.setCheckable(False)

        self.gridLayout_4.addWidget(self.pushButton_delete_figures, 0, 7, 1, 1)

        self.pushButton_pencil = QPushButton(self.groupBox_painting)
        self.pushButton_pencil.setObjectName(u"pushButton_pencil")
        self.pushButton_pencil.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_pencil.sizePolicy().hasHeightForWidth())
        self.pushButton_pencil.setSizePolicy(sizePolicy)
        self.pushButton_pencil.setMinimumSize(QSize(40, 40))
        self.pushButton_pencil.setMaximumSize(QSize(40, 40))
        self.pushButton_pencil.setIconSize(QSize(35, 35))
        self.pushButton_pencil.setCheckable(True)

        self.gridLayout_4.addWidget(self.pushButton_pencil, 0, 8, 1, 1)

        self.pushButton_delete_pencil = QPushButton(self.groupBox_painting)
        self.pushButton_delete_pencil.setObjectName(u"pushButton_delete_pencil")
        self.pushButton_delete_pencil.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_delete_pencil.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_pencil.setSizePolicy(sizePolicy)
        self.pushButton_delete_pencil.setMinimumSize(QSize(40, 40))
        self.pushButton_delete_pencil.setMaximumSize(QSize(40, 40))
        self.pushButton_delete_pencil.setIconSize(QSize(35, 35))
        self.pushButton_delete_pencil.setCheckable(False)

        self.gridLayout_4.addWidget(self.pushButton_delete_pencil, 0, 9, 1, 1)


        self.horizontalLayout_painting_2.addWidget(self.groupBox_painting)


        self.formLayout_bot.setLayout(0, QFormLayout.LabelRole, self.horizontalLayout_painting_2)

        self.groupBox_label = QGroupBox(self.centralwidget)
        self.groupBox_label.setObjectName(u"groupBox_label")
        self.groupBox_label.setMinimumSize(QSize(501, 61))
        self.groupBox_label.setMaximumSize(QSize(501, 61))
        self.gridLayout_5 = QGridLayout(self.groupBox_label)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.pushButton_label = QPushButton(self.groupBox_label)
        self.pushButton_label.setObjectName(u"pushButton_label")
        self.pushButton_label.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_label.sizePolicy().hasHeightForWidth())
        self.pushButton_label.setSizePolicy(sizePolicy)
        self.pushButton_label.setMinimumSize(QSize(40, 40))
        self.pushButton_label.setMaximumSize(QSize(40, 40))
        self.pushButton_label.setIconSize(QSize(35, 35))
        self.pushButton_label.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_label, 0, 0, 1, 1)

        self.pushButton_delete_labels = QPushButton(self.groupBox_label)
        self.pushButton_delete_labels.setObjectName(u"pushButton_delete_labels")
        self.pushButton_delete_labels.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_delete_labels.sizePolicy().hasHeightForWidth())
        self.pushButton_delete_labels.setSizePolicy(sizePolicy)
        self.pushButton_delete_labels.setMinimumSize(QSize(40, 40))
        self.pushButton_delete_labels.setMaximumSize(QSize(40, 40))
        self.pushButton_delete_labels.setIconSize(QSize(35, 35))
        self.pushButton_delete_labels.setCheckable(False)

        self.gridLayout_5.addWidget(self.pushButton_delete_labels, 0, 1, 1, 1)

        self.fontComboBox = QFontComboBox(self.groupBox_label)
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.fontComboBox.setEnabled(False)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setMinimumSize(QSize(225, 25))
        self.fontComboBox.setMaximumSize(QSize(225, 25))
        self.fontComboBox.setFont(font)
        self.fontComboBox.setEditable(False)
        self.fontComboBox.setCurrentIndex(211)
        self.fontComboBox.setFontFilters(QFontComboBox.ScalableFonts)
        font3 = QFont()
        font3.setFamilies([u"Times New Roman"])
        self.fontComboBox.setCurrentFont(font3)

        self.gridLayout_5.addWidget(self.fontComboBox, 0, 2, 1, 1)

        self.comboBox_font_size = QComboBox(self.groupBox_label)
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.addItem("")
        self.comboBox_font_size.setObjectName(u"comboBox_font_size")
        self.comboBox_font_size.setEnabled(False)
        self.comboBox_font_size.setMinimumSize(QSize(45, 25))
        self.comboBox_font_size.setMaximumSize(QSize(45, 25))
        self.comboBox_font_size.setFont(font)

        self.gridLayout_5.addWidget(self.comboBox_font_size, 0, 3, 1, 1)

        self.pushButton_bold = QPushButton(self.groupBox_label)
        self.pushButton_bold.setObjectName(u"pushButton_bold")
        self.pushButton_bold.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_bold.sizePolicy().hasHeightForWidth())
        self.pushButton_bold.setSizePolicy(sizePolicy)
        self.pushButton_bold.setMinimumSize(QSize(30, 25))
        self.pushButton_bold.setMaximumSize(QSize(30, 25))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        self.pushButton_bold.setFont(font4)
        self.pushButton_bold.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_bold, 0, 4, 1, 1)

        self.pushButton_italic = QPushButton(self.groupBox_label)
        self.pushButton_italic.setObjectName(u"pushButton_italic")
        self.pushButton_italic.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_italic.sizePolicy().hasHeightForWidth())
        self.pushButton_italic.setSizePolicy(sizePolicy)
        self.pushButton_italic.setMinimumSize(QSize(30, 25))
        self.pushButton_italic.setMaximumSize(QSize(30, 25))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setItalic(True)
        self.pushButton_italic.setFont(font5)
        self.pushButton_italic.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_italic, 0, 5, 1, 1)

        self.pushButton_underline = QPushButton(self.groupBox_label)
        self.pushButton_underline.setObjectName(u"pushButton_underline")
        self.pushButton_underline.setEnabled(False)
        sizePolicy.setHeightForWidth(self.pushButton_underline.sizePolicy().hasHeightForWidth())
        self.pushButton_underline.setSizePolicy(sizePolicy)
        self.pushButton_underline.setMinimumSize(QSize(30, 25))
        self.pushButton_underline.setMaximumSize(QSize(30, 25))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setUnderline(True)
        self.pushButton_underline.setFont(font6)
        self.pushButton_underline.setCheckable(True)

        self.gridLayout_5.addWidget(self.pushButton_underline, 0, 6, 1, 1)


        self.formLayout_bot.setWidget(0, QFormLayout.FieldRole, self.groupBox_label)


        self.gridLayout_7.addLayout(self.formLayout_bot, 1, 0, 1, 1)

        self.test_func = QPushButton(self.centralwidget)
        self.test_func.setObjectName(u"test_func")
        sizePolicy.setHeightForWidth(self.test_func.sizePolicy().hasHeightForWidth())
        self.test_func.setSizePolicy(sizePolicy)
        self.test_func.setMinimumSize(QSize(150, 25))
        self.test_func.setMaximumSize(QSize(150, 25))
        self.test_func.setFont(font)

        self.gridLayout_7.addWidget(self.test_func, 1, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1466, 21))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_additional = QMenu(self.menubar)
        self.menu_additional.setObjectName(u"menu_additional")
        self.menu_theme = QMenu(self.menu_additional)
        self.menu_theme.setObjectName(u"menu_theme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_main = QToolBar(MainWindow)
        self.toolBar_main.setObjectName(u"toolBar_main")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar_main)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_additional.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_new_scheme)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_all)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_help.addAction(self.action_about)
        self.menu_additional.addAction(self.action_presentation_mode)
        self.menu_additional.addAction(self.action_QB_Wrist)
        self.menu_additional.addSeparator()
        self.menu_additional.addAction(self.menu_theme.menuAction())
        self.menu_theme.addAction(self.action_light_theme)
        self.menu_theme.addAction(self.action_dark_theme)
        self.toolBar_main.addAction(self.action_new_scheme)
        self.toolBar_main.addAction(self.action_save)
        self.toolBar_main.addAction(self.action_save_all)
        self.toolBar_main.addAction(self.action_presentation_mode)
        self.toolBar_main.addAction(self.action_QB_Wrist)

        self.retranslateUi(MainWindow)

        self.tabWidget_game_type.setCurrentIndex(0)
        self.comboBox_line_thickness.setCurrentIndex(0)
        self.comboBox_font_size.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PlayCreator", None))
        self.action_save.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c", None))
#if QT_CONFIG(tooltip)
        self.action_save.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c (Ctrl + S)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0445\u043e\u0434", None))
#if QT_CONFIG(statustip)
        self.action_exit.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
#if QT_CONFIG(statustip)
        self.action_about.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041e \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0435", None))
#endif // QT_CONFIG(statustip)
        self.action_presentation_mode.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0436\u0438\u043c \u043f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u0438", None))
#if QT_CONFIG(statustip)
        self.action_presentation_mode.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0436\u0438\u043c \u043f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u0438", None))
#endif // QT_CONFIG(statustip)
        self.action_QB_Wrist.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0434\u0435\u043b\u0430\u0442\u044c \"QB Wrist\"", None))
        self.action_light_theme.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0432\u0435\u0442\u043b\u0430\u044f", None))
#if QT_CONFIG(statustip)
        self.action_light_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u0432\u0435\u0442\u043b\u0430\u044f \u0442\u0435\u043c\u0430", None))
#endif // QT_CONFIG(statustip)
        self.action_dark_theme.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0451\u043c\u043d\u0430\u044f", None))
#if QT_CONFIG(statustip)
        self.action_dark_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u0451\u043c\u043d\u0430\u044f \u0442\u0435\u043c\u0430", None))
#endif // QT_CONFIG(statustip)
        self.action_new_scheme.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u0432\u0430\u044f \u0441\u0445\u0435\u043c\u0430", None))
#if QT_CONFIG(tooltip)
        self.action_new_scheme.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + N", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_new_scheme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u0432\u0430\u044f \u0441\u0445\u0435\u043c\u0430 (Ctrl + N)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_new_scheme.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_all.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0432\u0441\u0451", None))
#if QT_CONFIG(tooltip)
        self.action_save_all.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + Shift + S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_save_all.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0432\u0441\u0451 (Ctrl + Shift + S)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.action_save_all.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.label_current_zoom.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u0438\u0431\u043b\u0438\u0436\u0435\u043d\u0438\u0435: 0%", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_additional_off_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_additional_off_football.setText(QCoreApplication.translate("MainWindow", u"+1", None))
#if QT_CONFIG(statustip)
        self.pushButton_del_additional_off_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_del_additional_off_football.setText(QCoreApplication.translate("MainWindow", u"-1", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_second_team_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0432\u0442\u043e\u0440\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_second_team_football.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043f\u0440\u043e\u0442\u0438\u0432\u043d\u0438\u043a\u043e\u0432", None))
#if QT_CONFIG(statustip)
        self.pushButton_delete_second_team_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0442\u043e\u0440\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_second_team_football.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043f\u0440\u043e\u0442\u0438\u0432\u043d\u0438\u043a\u043e\u0432", None))
        self.label_place_players_football.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443:", None))
        self.comboBox_team_type_football.setItemText(0, QCoreApplication.translate("MainWindow", u"\u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
        self.comboBox_team_type_football.setItemText(1, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043a\u0438\u043a\u043e\u0444\u0430", None))
        self.comboBox_team_type_football.setItemText(2, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043f\u0430\u043d\u0442\u0430", None))
        self.comboBox_team_type_football.setItemText(3, QCoreApplication.translate("MainWindow", u"\u043f\u0440\u043e\u0431\u0438\u0442\u0438\u044f \u043f\u043e \u0432\u043e\u0440\u043e\u0442\u0430\u043c", None))

#if QT_CONFIG(statustip)
        self.comboBox_team_type_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0442\u0438\u043f\u0430 \u043a\u043e\u043c\u0430\u043d\u0434\u044b", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.pushButton_delete_all_players_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445 \u0438\u0433\u0440\u043e\u043a\u043e\u0432", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_all_players_football.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445", None))
        self.label_yards_football.setText(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b:", None))
#if QT_CONFIG(statustip)
        self.lineEdit_yards_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_yards_football.setInputMask(QCoreApplication.translate("MainWindow", u"99", None))
        self.lineEdit_yards_football.setText(QCoreApplication.translate("MainWindow", u"50", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_first_team_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043f\u0435\u0440\u0432\u0443\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_first_team_football.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c", None))
#if QT_CONFIG(statustip)
        self.pushButton_edit_scheme_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0445\u0435\u043c\u044b", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_edit_scheme_football.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_scheme_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_scheme_football.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(statustip)
        self.pushButton_delete_scheme_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_scheme_football.setText(QCoreApplication.translate("MainWindow", u"-", None))
#if QT_CONFIG(statustip)
        self.pushButton_scheme_move_up_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u0432\u0435\u0440\u0445", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_scheme_move_up_football.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
#if QT_CONFIG(statustip)
        self.pushButton_scheme_move_down_football.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u043d\u0438\u0437", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_scheme_move_down_football.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
        self.tabWidget_game_type.setTabText(self.tabWidget_game_type.indexOf(self.tab_football), QCoreApplication.translate("MainWindow", u"\u0424\u0443\u0442\u0431\u043e\u043b", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_def_team_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u0437\u0430\u0449\u0438\u0442\u044b", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_def_team_flag.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0437\u0430\u0449\u0438\u0442\u0443", None))
#if QT_CONFIG(statustip)
        self.pushButton_delete_def_team_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u0437\u0430\u0449\u0438\u0442\u044b", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_def_team_flag.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0437\u0430\u0449\u0438\u0442\u0443", None))
        self.label_yards_flag.setText(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b:", None))
#if QT_CONFIG(statustip)
        self.lineEdit_yards_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u042f\u0440\u0434\u044b \u0434\u043e \u0437\u0430\u0447\u0451\u0442\u043d\u043e\u0439 \u0437\u043e\u043d\u044b", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_yards_flag.setInputMask(QCoreApplication.translate("MainWindow", u"99", None))
        self.lineEdit_yards_flag.setText(QCoreApplication.translate("MainWindow", u"25", None))
#if QT_CONFIG(statustip)
        self.pushButton_delete_all_players_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445 \u0438\u0433\u0440\u043e\u043a\u043e\u0432", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_all_players_flag.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435\u0445", None))
#if QT_CONFIG(statustip)
        self.pushButton_place_off_team_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043a\u043e\u043c\u0430\u043d\u0434\u0443 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_place_off_team_flag.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u0435", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_additional_off_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_additional_off_flag.setText(QCoreApplication.translate("MainWindow", u"+1", None))
#if QT_CONFIG(statustip)
        self.pushButton_del_additional_off_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u0438\u0433\u0440\u043e\u043a\u0430 \u043d\u0430\u043f\u0430\u0434\u0435\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_del_additional_off_flag.setText(QCoreApplication.translate("MainWindow", u"-1", None))
#if QT_CONFIG(statustip)
        self.pushButton_edit_scheme_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0445\u0435\u043c\u044b", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_edit_scheme_flag.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435", None))
#if QT_CONFIG(statustip)
        self.pushButton_add_scheme_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_add_scheme_flag.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(statustip)
        self.pushButton_delete_scheme_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_scheme_flag.setText(QCoreApplication.translate("MainWindow", u"-", None))
#if QT_CONFIG(statustip)
        self.pushButton_scheme_move_up_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u0432\u0435\u0440\u0445", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_scheme_move_up_flag.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
#if QT_CONFIG(statustip)
        self.pushButton_scheme_move_down_flag.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u043c\u0435\u0441\u0442\u0438\u0442\u044c \u0441\u0445\u0435\u043c\u0443 \u0432\u043d\u0438\u0437", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_scheme_move_down_flag.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
        self.tabWidget_game_type.setTabText(self.tabWidget_game_type.indexOf(self.tab_flag), QCoreApplication.translate("MainWindow", u"\u0424\u043b\u0430\u0433-\u0444\u0443\u0442\u0431\u043e\u043b", None))
        self.groupBox_move_erase.setTitle("")
#if QT_CONFIG(tooltip)
        self.pushButton_move.setToolTip(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_move.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0435\u0440\u0435\u0442\u0430\u0441\u043a\u0438\u0432\u0430\u043d\u0438\u0435 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u043e\u0432 (S)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_move.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_move.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_erase.setToolTip(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_erase.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u043e\u0442\u0434\u0435\u043b\u044c\u043d\u043e\u0433\u043e \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u0430 (D)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_erase.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_erase.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_colors.setTitle("")
#if QT_CONFIG(statustip)
        self.pushButton_current_color.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u0446\u0432\u0435\u0442 / \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u0441\u0432\u043e\u0439 \u0446\u0432\u0435\u0442", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_current_color.setText("")
        self.pushButton_color_10.setText("")
        self.pushButton_color_9.setText("")
        self.pushButton_color_4.setText("")
        self.pushButton_color_6.setText("")
        self.pushButton_color_7.setText("")
        self.pushButton_color_1.setText("")
        self.pushButton_color_8.setText("")
        self.pushButton_color_2.setText("")
        self.pushButton_color_3.setText("")
        self.pushButton_color_0.setText("")
        self.pushButton_color_5.setText("")
        self.pushButton_color_11.setText("")
        self.groupBox_painting.setTitle("")
        self.comboBox_line_thickness.setItemText(0, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_line_thickness.setItemText(1, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_line_thickness.setItemText(2, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_line_thickness.setItemText(3, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_line_thickness.setItemText(4, QCoreApplication.translate("MainWindow", u"6", None))

#if QT_CONFIG(statustip)
        self.comboBox_line_thickness.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0422\u043e\u043b\u0449\u0438\u043d\u0430 \u043b\u0438\u043d\u0438\u0439", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton_route.setToolTip(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_route.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0440\u0448\u0440\u0443\u0442\u0430 (Q)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_route.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_route.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_block.setToolTip(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_block.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u0431\u043b\u043e\u043a\u0430 (W)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_block.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_block.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_motion.setToolTip(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_motion.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043c\u043e\u0443\u0448\u0435\u043d\u0430 (E)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_motion.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_motion.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_delete_actions.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + Q", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_delete_actions.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0439 \u0438\u0433\u0440\u043e\u043a\u043e\u0432 (Ctrl + Q)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_actions.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_delete_actions.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_rectangle.setToolTip(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_rectangle.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u044f\u043c\u043e\u0443\u0433\u043e\u043b\u044c\u043d\u0438\u043a\u0430 (R)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_rectangle.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_rectangle.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_ellipse.setToolTip(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_ellipse.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u044d\u043b\u043b\u0438\u043f\u0441\u0430 (T)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_ellipse.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_ellipse.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_delete_figures.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + R", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_delete_figures.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u0444\u0438\u0433\u0443\u0440 (Ctrl + R)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_figures.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_delete_figures.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_pencil.setToolTip(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_pencil.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0438\u0441\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u043e\u043c (F)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_pencil.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_pencil.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_delete_pencil.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + F", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_delete_pencil.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u043a\u0430\u0440\u0430\u043d\u0434\u0430\u0448\u0430 (Ctrl + F)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_pencil.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_delete_pencil.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox_label.setTitle("")
#if QT_CONFIG(tooltip)
        self.pushButton_label.setToolTip(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_label.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u0435 \u043d\u0430\u0434\u043f\u0438\u0441\u0435\u0439 (C)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_label.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_label.setShortcut(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_delete_labels.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl + C", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_delete_labels.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0423\u0434\u0430\u043b\u0435\u043d\u0438\u0435 \u0432\u0441\u0435\u0445 \u043d\u0430\u0434\u043f\u0438\u0441\u0435\u0439 (Ctrl + C)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_delete_labels.setText("")
#if QT_CONFIG(shortcut)
        self.pushButton_delete_labels.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(statustip)
        self.fontComboBox.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 \u0448\u0440\u0438\u0444\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
        self.comboBox_font_size.setItemText(0, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_font_size.setItemText(1, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_font_size.setItemText(2, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_font_size.setItemText(3, QCoreApplication.translate("MainWindow", u"11", None))
        self.comboBox_font_size.setItemText(4, QCoreApplication.translate("MainWindow", u"12", None))
        self.comboBox_font_size.setItemText(5, QCoreApplication.translate("MainWindow", u"14", None))
        self.comboBox_font_size.setItemText(6, QCoreApplication.translate("MainWindow", u"16", None))
        self.comboBox_font_size.setItemText(7, QCoreApplication.translate("MainWindow", u"18", None))
        self.comboBox_font_size.setItemText(8, QCoreApplication.translate("MainWindow", u"20", None))
        self.comboBox_font_size.setItemText(9, QCoreApplication.translate("MainWindow", u"22", None))
        self.comboBox_font_size.setItemText(10, QCoreApplication.translate("MainWindow", u"24", None))
        self.comboBox_font_size.setItemText(11, QCoreApplication.translate("MainWindow", u"26", None))
        self.comboBox_font_size.setItemText(12, QCoreApplication.translate("MainWindow", u"28", None))
        self.comboBox_font_size.setItemText(13, QCoreApplication.translate("MainWindow", u"36", None))

#if QT_CONFIG(statustip)
        self.comboBox_font_size.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0437\u043c\u0435\u0440 \u0448\u0440\u0438\u0444\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton_bold.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_bold.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0416\u0438\u0440\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442 (Ctrl+B)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_bold.setText(QCoreApplication.translate("MainWindow", u"\u0416", None))
#if QT_CONFIG(shortcut)
        self.pushButton_bold.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_italic.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_italic.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u0440\u0441\u0438\u0432 (Ctrl+I)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_italic.setText(QCoreApplication.translate("MainWindow", u"\u041a", None))
#if QT_CONFIG(shortcut)
        self.pushButton_italic.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.pushButton_underline.setToolTip(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_underline.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u0447\u0451\u0440\u043a\u0438\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u043a\u0441\u0442\u0430 (Ctrl+U)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_underline.setText(QCoreApplication.translate("MainWindow", u"\u0427", None))
#if QT_CONFIG(shortcut)
        self.pushButton_underline.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.test_func.setText(QCoreApplication.translate("MainWindow", u"test_func", None))
        self.menu_file.setTitle(QCoreApplication.translate("MainWindow", u"\u0424\u0430\u0438\u043b", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043c\u043e\u0449\u044c", None))
        self.menu_additional.setTitle(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e", None))
#if QT_CONFIG(statustip)
        self.menu_theme.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0442\u0435\u043c\u0443", None))
#endif // QT_CONFIG(statustip)
        self.menu_theme.setTitle(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043c\u0430", None))
        self.toolBar_main.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

